apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  project: default
  source:
    path: manifests/
    repoURL: https://github.com/coreos/kube-prometheus-stack.git
    targetRevision: master
