apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Apps enabled for this cluster
  - ../../base

  # Monitoring
  # - ../../../apps/monitoring/prometheus/overlays/start_cluster
