kube-prometheus-stack:
  namespace: monitoring
  global:
    imagePullSecrets:
      - name: "docker-registry"
  grafana:
    enabled: true
  prometheus:
    enabled: true
    serviceAccount:
      create: true
      name: chart-default-prometheus
      annotations:
        eks.amazonaws.com/role-arn: "arn:aws:iam::xxxxxxxxxxxx:role/cluster1-prometheus"
    thanosService:
      enabled: true
      portName: grpc
      port: 10901
      targetPort: "grpc"
    prometheusSpec:
      externalLabels:
        environment: prod
        cluster: main_cluster
      replicas: 2
      shards: 1
      retention: 30d
      podMonitorSelectorNilUsesHelmValues: false
      serviceMonitorSelectorNilUsesHelmValues: false
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: gp2
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 100Gi
      thanos:
        image: thanosio/thanos:v0.17.2
        objectStorageConfig:
          key: thanos-objstore.yaml
          name: thanos-objstore-config
        resources:
          limits:
            cpu: 1000m
            memory: 1024Mi
          requests:
            cpu: 300m
            memory: 512Mi
